### PR TITLE
Fix remove other packages classes from inventory

### PR DESCRIPTION
**Pull request by lucaslaurent04**
Remove classes extended in inventory packages that were from other symbiose packages.

### CODE REVIEW

**Comment by ghost** [comment]
I recommend you initialize the 'sale' package and verify that everything works

**Comment by lucaslaurent04** [comment]
> I recommend you initialize the 'sale' package and verify that everything works

Hey, if I import data from sale package and then inventory package, the entries of sale are overwritten by the one of inventory. So It works when testing only inventory, but if we want multiple packages to be importable and work, we should not overwrite items previously imported in dependency packages.

We need to think how we can manage multi packages imports.

**Comment by ghost** [comment]
First, we can simplify the initial data for the sales package, and then update the initial date for the inventory package.
Also, we need to pay attention to the customer class that requires initial data of the identity package, if we aim to maintain coherence.

**Comment by ghost** [comment]
This Pull Request should be accepted as it simplifies the code significantly, making it easier to maintain. 
The simplification involves removing redundancies and improving readability.

However, I recommend you initialize the 'inventory' package and verify that everything works.

**Pull request merged**
